
CREATE TABLE IF NOT EXISTS documents (
  id UUID PRIMARY KEY,
  base_path TEXT NOT NULL,
  filename TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
