FROM node:20 as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20 as production

WORKDIR /app
COPY --from=build /app/dist ./dist
CMD ["node", "dist/index.js"]
